name: Release
on:
  push:
    tags:
      - "*"
jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup build env for Linux
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
            | gpg --dearmor \
            | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
              https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
            | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
          sudo apt-get update -qq
          sudo apt install -y podman qemu-user-static
          sudo systemctl start systemd-binfmt.service
          podman info

      - name: Build for Linux x86_64
        run: |
          podman build -f Containerfile --output artifacts .
          mv artifacts/tmux tmux-linux-x86_64

      - name: Build for Linux arm64
        run: |
          podman build --arch=arm64 -f Containerfile --output artifacts .
          mv artifacts/tmux tmux-linux-arm64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: "Tmux binaries"
          files: "tmux*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
